### ISSUE TITLE
Prepositions can be reset to none by the editor

### ISSUE THREAD

**Issue by Omikhleia** [doughsay/room.js-client#4]
Small issue when creating a verb such as:
```
object.use = new Verb("use", 'this", "to", "any")
```
or even
```
object.use = new Verb("use", 'this", "to/at", "any")
```
And hitting Ctrl-p to edit it: then the editor resets the preposition to "none" - which renders the command inefficient when you inadvertently save your edits without noticing this ;)

That's seemingly because there is not match in the select box for prepositions.
- Either choose the closest match (in that case that would "at/to", which is likely to be appropriate)
- Or rather allow more types of combination  but it probably means replacing the select box by a drop-down menu with checkboxes ^^

It's very minor, since most of the time one would just do `new Verb("use")` and fill everything else in the editor, but I did notice it while creating a bunch of verbs in a row, for later editing.

**Comment by doughsay** [comment]
Good catch, but I think the bug here is that `new Verb(...)` should throw an error if you supply an invalid `dobjarg`, `preparg` or `iobjarg`.  "to" in this case is not valid, "to/at" being the valid one.  I'm not sure the parser would have matched correctly with the `preparg` set to just "to".  Maybe I'm wrong though?

In any cause, the bug is in the server not the client I believe, so I'll close this one for now.
